services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: BID-AI-EVALUATION
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123456@db:5432/BID-AI-EVALUATION
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}

volumes:
  pgdata:

